### ISSUE TITLE
Doesn't work with browserify or webpack.

### ISSUE THREAD

**Issue by quadrupleslap** [SheetJS/js-xlsx#285] opened 2015-08-11 08:41 UTC
In webpack I get this error:

``` sh
ERROR in ../~/xlsx/xlsx.js
Module not found: Error: Cannot resolve module 'fs' in /Users/Ram/Desktop/bob/node_modules/xlsx
 @ ../~/xlsx/xlsx.js 32:3635-3648 33:3206-3224

ERROR in ../~/xlsx/ods.js
Module not found: Error: Cannot resolve module 'fs' in /Users/Ram/Desktop/bob/node_modules/xlsx
 @ ../~/xlsx/ods.js 67:9-27

ERROR in ../~/xlsx/dist/cpexcel.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cptable in /Users/Ram/Desktop/bob/node_modules/xlsx/dist
 @ ../~/xlsx/dist/cpexcel.js 1:165488-165513
```

**Comment by alisonatwork** [comment] 2015-08-13 08:20
I hit the same problem yesterday. It seems like Webpack is trying to eagerly resolve the ```require``` statements and then failing because we are not running inside Node. I have a really quick and dirty fork @ https://github.com/alisonatwork/js-xlsx that basically just comments out all the bad stuff in ```xlsx.js```, but a better fix is needed. It would be nice to tweak the ```Makefile``` and ```bits/*``` so that we could compile a browser-friendly version that doesn't include any of the server-side functionality at all, perhaps using some kind of JS version of ```#ifdef```.

**Comment by quadrupleslap** [comment] 2015-08-14 13:30
Yeah, unfortunately I ended up doing the same thing. Luckily ZipJS doesn't use any Node APIs, so making this change shouldn't be too hard using something like envify + uglify.

**Comment by barbalex** [comment] 2015-08-28 13:33
same problem here, same solution - but it IS a bad hack

**Comment by alisonatwork** [comment] 2015-09-09 13:24
Okay I went down a really dark rabbit-hole of trying to alter my fork so that it would work both in Webpack and not in Webpack, but it's just too hard. Honestly, the only way it would work nicely is if we generated two different artifacts, which would break npm and stop us from being able to include it as a dependency in package.json.
So, new workaround for me was to give up and just include the .min.js file using script-loader, which tells Webpack to bypass require() parsing. That also means you end up with XLSX declared globally (on window), but at least we don't need to build a custom fork of the library. Not sure if Browserify has the same feature, but then that might be a good incentive to move to Webpack ;-)

**Comment by barbalex** [comment] 2015-09-09 13:49
@alisonatwork thanks a lot - this is the best solution so far!

**Comment by chavezom** [comment] 2015-10-15 22:16
Hi @alisonatwork, can you give me some details of your workaround, how do you require the .min.js using script-loader?

**Comment by alisonatwork** [comment] 2015-10-16 10:48
@chavezom it looks like this:
```javascript
        require.ensure(['xlsx/dist/xlsx.core.min'], function(require) {
            require('xlsx/dist/xlsx.core.min');
            handleXlsFile(file, window.XLSX);
        }, 'js-xlsx');
```
Then in your webpack config:
```javascript
               { // for third-party minified scripts, don't process require()
                    test: /\.min\.js$/,
                    include: /(node_modules|bower_components)/,
                    loader: 'script'
                },
```
Or something similar. Hope that helps.

**Comment by chavezom** [comment] 2015-10-16 14:32
Thanks @alisonatwork

**Comment by whytheday** [comment] 2015-11-28 14:35
I was able to get it building by adding the following to my webpack config:
```javascript
    node: {
            fs: 'empty'
    },
    externals: [
        {
            './cptable': 'var cptable'
        }
    ]
```

**Comment by Prometheuser** [comment] 2016-01-04 09:22
Thanks a lot, it works for me!!!!!! @whytheday

**Comment by piotrblasiak** [comment] 2016-01-28 15:22
@whytheday that solved it for me too, good job figuring it out! Thanks!

**Comment by cubbuk** [comment] 2016-02-11 09:11
Thanks @whytheday for the solution.

**Comment by jamesjnadeau** [comment] 2016-02-24 17:39
@whytheday I owe you a beverage, ty! Hope this brings a smile to your day!

**Comment by botezalexandru** [comment] 2016-03-28 11:39
@whytheday Thanks to you i was able to figure it out, thanks.

**Comment by akhnaeton** [comment] 2016-05-25 15:58
Hi:
I had the same problem and I resolved it by doing this:
```
module.exports = {
    // (...)
    plugins: [
        // (...)
        new webpack.IgnorePlugin(/cptable/)
    ],
    node: {
        fs: "empty"
    },
    externals: [
        {  "./cptable": "var cptable",  "./jszip": "jszip" }
    ]
};
```
This solved the problem, but another one arised.  Now, whenever I execute:
`var workbook = XLSX.readFile('myfile.xlsx');`
...an error is thrown in my browser:
`Uncaught TypeError: _fs.readFileSync is not a function     (xlsx.js:11387)`

**Any ideas?**

**Comment by arirawr** [comment] 2016-05-27 01:23
Still having the error mentioned above.

**Comment by akhnaeton** [comment] 2016-05-28 13:56
Yes, I keep searching and searching and my conclusion is that **this library simply isn't compatible with webpack and react js**.  You can modify the webpack config all you want, but, unless there's a setting that you can configure in webpack that lets React/Webpack work with the filesystem (client-side), then there's no chance to put it to work for us.  Maybe I'm wrong, but, any library that has a dependency on "fs" will explode, one way or the other.  I think the best way to approach a solution is to work with XLSX server-side:  upload the excel file to the server and work with it there, then return the desired result to the client.

Your opinion on this is very very valuable and well appreciated.

**Comment by arirawr** [comment] 2016-05-28 16:37
@akhnaeton I've come to that conclusion as well, I started setting up a small node server to do the conversion on.

**Comment by whytheday** [comment] 2016-05-31 13:21
@akhnaeton @arirawr It doesn't look like XLSX.readFile is meant for the browser: https://github.com/SheetJS/js-xlsx#parsing-workbooks. Looks like you should be using XLSX.read.

**Comment by coreymcdermott** [comment] 2016-07-26 09:54
Thanks  @whytheday - Greatly appreciated.

**Comment by ArnieGA** [comment] 2016-07-26 14:10
@whytheday:  Yep! You're right. The functions that read, are reading A FILE
so they use node's FS and that operation is not allowed from the client
side. Browsers don't allow it for security reasons, which makes total
sense. My solution involved uploading the file to the server so it can use
js-xlsx there and then respond with data.   Many thanks!

**Comment by geekgugi** [comment] 2016-08-18 10:04
I am able to solve this using @whytheday's solution. For the warning related jszip, I used `module.noParse` option available in webpack config.
`WARNING in ./~/xlsx/jszip.js
Critical dependencies:
12:436-443 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/xlsx/jszip.js 12:436-443`

The final webpack config had 
  `module: {
    noParse: [/jszip.js$/],
  },`

**Comment by TechBK** [comment] 2016-09-25 19:22
hello everyone, i am using `js-xlsx` on react-native `context`.
Plzz show me how to fix this problem ?

**Comment by HereThereBeMonsters** [comment] 2016-11-18 13:31
About loading files client-side in the browser : you can use the HTML5 File API to load the content of an Excel file selected by the user. Here is an example I used to be able to display to the user a list of the sheets contained in the XLS file (in Angular 2) :

 ```
fileSelected(event:any){
        let file:File = event.srcElement.files[0];
        if(!file){
            console.log('No file picked.');
            return;
        }

        console.log('Loading file : ' + file.name);
        let reader:FileReader = new FileReader();
        reader.addEventListener('loadend', () => {
            this.excelFileSize = Math.floor(file.size / 1024) + 'KB';
            console.log('Finished loading file ' + file.name);
            //let dataUrl:string = reader.result;
            this.data.excelFileContent = this.dataUrlToBase64(reader.result);

            this.data.excelFileName = file.name;

            this.extractExcelSheetNames();
        });

        reader.readAsDataURL(file);
    }

    private extractExcelSheetNames() {
        let workbook = XLSX.read(this.data.excelFileContent, {type: 'base64'});
        this.excelSheetNames = workbook.SheetNames;
        this.data.excelSheetName = this.excelSheetNames[0];
    }

    private dataUrlToBase64(dataUrl:string):string{
        let i:number = dataUrl.indexOf(',') + 1;
        return dataUrl.substring(i);
    }
```
And the HTML : 

`<input type="file" (change)="fileSelected($event)" accept=".xls,.xlsx" />`

**Comment by fyyyyy** [comment] 2016-12-01 14:29
Including it via CDN and script tag seems to be the only viable option for now
`<script src="https://cdn.jsdelivr.net/js-xlsx/0.8.0/xlsx.full.min.js"></script>`

**Comment by SheetJSDev** [comment] 2017-02-13 18:46
I'm not too familiar with webpack or browserify.  The original use cases were in browser with direct script references (e.g. `<script src="xlsx.js"></script>`) or in node (e.g. `var XLSX = require('xlsx')`).  All of the node-related behaviors are guarded with typeof checks.  For example, the fs module is required only in the case where `exports` and `module` are available:

```
var _fs, jszip;
//...
if (typeof exports !== 'undefined') {
	if (typeof module !== 'undefined' && module.exports) {
		//...
		_fs = require('f'+'s');
	}
}
```

In https://github.com/substack/node-browserify/issues/805 we ultimately decided to address browserify issues by breaking the require strings as done above.

The `xlsx.core.min.js` and `xlsx.core.full.js` scripts combine the dependencies already, so in theory you should just be able to add a script reference in your code and everything should just work.  What settings are required to suppress the webpack require magic for this library?

**Comment by klaszlo** [comment] 2017-02-17 14:05
SheetJSDev: I would like to point you to showdown.js project (a markdown highlighter).

Especially to shese lines, where it tests for browser, AMD loader and commonjs(node) loader:
https://github.com/showdownjs/showdown/blob/master/dist/showdown.js#L2753-L2770

I hope it helps in this case.

**Comment by SheetJSDev** [comment] 2017-02-18 04:04
@klaszlo yeah I ran into the same frustration.  The module systems basically assume you want to use the `require` code paths in the browser and there's no obvious way to communicate that you don't want to do that.

**Comment by enq-asantikari** [comment] 2017-02-24 13:50
I am using [xlsx-style](https://www.npmjs.com/package/xlsx-style) plugin  with Angular 2 created using @angular/cli ver 1.0.0-beta.32.3 and I am not able to fix the issue as mentioned by @alisonatwork. I imported  by creating a .d.ts file but it seems  it still misses cpexcel. I am not able to find any webpack configuration in the project :( .

**Comment by feload** [comment] 2017-02-24 17:30
After trying all your suggestions, I ended up doing something like this:

`import 'script-loader!../../../node_modules/xlsx/dist/xlsx.full.min.js';`

I hope this is useful for you.

**Comment by ashishsantikari** [comment] 2017-02-27 07:05
I tried as per your suggestion but still, that doesn't work.
I have provided GitHub repo for the demo. If you can fiddle around and provide me some suggestion, that would be great.

[GitHub repo](https://github.com/ashishsantikari/excel-export-angular2)

**Comment by SheetJSDev** [comment] 2017-03-05 01:21
We un-broke all of the require statements in 0.8.7 and included samples with browserify/requirejs/webpack.  Please check against the latest version

**Comment by jbrecht** [comment] 2017-03-08 19:53
@SheetJSDev - thanks! using 0.8.7 and the config example here:
https://github.com/SheetJS/js-xlsx/blob/master/demos/webpack/webpack.config.js
I was able to fix this.

**Comment by klaszlo** [comment] 2017-03-09 21:11
@SheetJSDev: I just finished importing js-xlsx project into my es6 project (via webpack). 
So basically I converted the js-xlsx sourcecode to es6, and corrected some jshint warnings.
(still many console.log everywhere:)
Are you interested in such 'dirty' code?

Another remark: You are using in the sourcecode almost everywhere `==` instead of `===`.
After correcting them to `===` and `!==` one bug surfaced:
https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L12702

You are testing if the variable is "`null`". I was unaware, that 

    opts == null
should be 

    (opts === null || typeof opts === 'undefined')

Is it intentional? Also you are mixing `v === undefined` and `typeof v === 'undefined'` 
throrough the code. Is it also intentional?

**Comment by SheetJSDev** [comment] 2017-03-09 21:27
@klaszlo if you have a repo, feel free to link and I'll take a look.  There are plenty of landmines in places like the `SSF` formatting code which will be addressed in due course.

**Comment by klaszlo** [comment] 2017-03-10 07:40
@SheetJSDev: I will clean up the code, and make a demo project with it. Give me a week or so.

**Comment by SheetJSDev** [comment] 2017-03-10 07:55
@klaszlo no rush :) we're also trying to resolve the packaging issues by fixing patterns in the dependencies.

**Comment by tosehee75** [comment] 2017-03-10 19:05
How do I get around this with angular-cli (angular 2)????

**Comment by SheetJSDev** [comment] 2017-03-11 00:06
We just pushed 0.9.1 and repaired other weird require patterns.  At this point, to work with webpack you should only need to suppress the `node` behavior.  Please confirm that this is the case

**Comment by tosehee75** [comment] 2017-03-13 14:23
Can you elaborate on the 'node' behavior?

Where should I add that in webpack?

**Comment by SheetJSDev** [comment] 2017-03-13 14:24
@tosehee75 in the `webpack.config.js` script:

```js
module.exports = {
	/* ... */
	module: {
		noParse: [/jszip.js$/]
	},
	node: {
		fs: false,
		Buffer: false
	}
}
```

**Comment by tosehee75** [comment] 2017-03-13 14:34
I don't see this file at all in my angular-cli created project.

**Comment by tosehee75** [comment] 2017-03-13 14:41
Updated to 0.9,2 and it doesn't give me any warnings or compile errors. For some reason, I don't have/need the webpack.config.js

**Comment by SheetJSDev** [comment] 2017-03-13 14:44
At this point I think the basic webpack/browserify concerns have been resolved. @quadrupleslap @alisonatwork @barbalex @chavezom @whytheday and everyone else, if you are encountering any issues please let us know.  We are closing this issue.

**Closed by SheetJSDev** 2017-03-13 14:44 UTC

**Comment by klaszlo** [comment] 2017-03-13 21:46
@SheetJSDev: Here is my test repo: https://github.com/klaszlo/jsxlsx-webpack
I modified js-xlsx inside `client/app/XLSXReaderService/vendor/*.js` files.
I also commented out all the node.js require statements, it is working for me for file reading on the client side.
I think you should separate the client and server side into separate files.

The test repo written in javascript es6, with angular 1.x (tested with angular 1.6), and with webpack. 
There is a mini tutorial inside the readme file.

Maybe my work is completely useless, although it took me a week to figure everything out, and deep dive into js-xlsx:)

Best,

**Comment by SheetJSDev** [comment] 2017-03-13 22:17
@klaszlo thanks for sharing! so I changed the code to load the npm version of xlsx rather than your vendored version, and I can confirm that the build fails when using xlsx@0.8.0 but passes with xlsx@0.9.2 -- running `webpack --env=dev --progress --colors --display-modules` shows:

```
   [3] ./~/xlsx/xlsx.js 454 kB {0} [built]
  [20] ./~/xlsx/dist/cpexcel.js 188 kB {0} [built]
  [21] ./~/xlsx/jszip.js 287 kB {0} [built]
```

I also added an examples page to the wiki: https://github.com/SheetJS/js-xlsx/wiki/Examples

**Comment by klaszlo** [comment] 2017-03-14 06:56
@SheetJSDev: Thank you for your review! At the example page (what you linked), 
there is just a link to my repo (but not your code change). 

Can you fork the project/send a pull request/publish a brand new repository, 
so we can update that test project? 

Maybe it is useful for someone else also.

**Comment by deju** [comment] 2017-03-31 08:24
@geekgugi You helped me. 👍

**Comment by chenEdgar** [comment] 2017-07-31 16:28
I got the same problem in the version of 0.10.7.

I try the above confirmed methods to solve my problem,  but finally fail.

![image](https://user-images.githubusercontent.com/12596622/28787436-ca97121a-764e-11e7-8873-af6c89a0bee0.png)


if my webpack.config have the following configs:

the first method, just ` module: {
        noParse: [/jszip.js$/]
    },`

the second:
`
node: {
            fs: 'empty'
    },
    externals: [
        {
            './cptable': 'var cptable'
        }
    ]
`

**Comment by reviewher** [comment] 2017-07-31 16:36
@chenEdgar are you requiring the minified file directly?  Can you check if requiring the root module `require('xlsx')` works?

**Comment by chenEdgar** [comment] 2017-08-01 01:06
@reviewher I imported the root module in exportXls.js module(the first picture). it worked for me in development environment if directly requiring the minified file in "index.html"( it use in jsx template and rendered by server side . the second picture), but the problem is `script` tag lost in build version.

**the first.**
![image](https://user-images.githubusercontent.com/12596622/28803552-0a78d5da-7690-11e7-8f49-77e2c68c46d2.png)

**the second.**
![image](https://user-images.githubusercontent.com/12596622/28803625-969c1608-7690-11e7-80b2-4dea919198e4.png)

**Comment by reviewher** [comment] 2017-08-01 01:24
@chenEdgar can you share a small project including the webpack config and the bare bits to reproduce this issue?

**Comment by chenEdgar** [comment] 2017-08-01 01:58
@reviewher thank you. later i will try to write a raw demo just using webpack and xlsx script.

**Comment by SheetJSDev** [comment] 2017-08-01 02:15
@chenEdgar we're going to change how the minified version is compiled.  It looks like the core issue is that you are pulling in the bower minified version, which is throwing off webpack.

We're also going to lock this thread, please raise a new issue.
