### ISSUE TITLE
HYPERLINK cell

### ISSUE THREAD

**Issue by slonoed** [SheetJS/js-xlsx#344] opened 2016-01-05 14:51 UTC
Could I create link cell when creating sheet?

**Comment by rylyade1** [comment] 2016-01-07 10:46
I have the same problem. Could someone help us out.

**Comment by rdeforest** [comment] 2016-01-07 23:34
I just ran into this myself. As far as I can tell there's no support for writing formuae in bits/67_wsxml.js.

**Comment by rdeforest** [comment] 2016-01-08 21:16
Just noticed this is a dupe of #156.

**Closed** 2017-03-31 00:57 UTC
Labels: Hyperlink

**Comment by Kalo7o** [comment] 2018-12-14 11:51
Same Problem.
