### ISSUE TITLE
Unsupported file 255

### ISSUE THREAD

**Issue by SHocker-Yu** [SheetJS/js-xlsx#575] opened 2017-03-01 06:32 UTC
this is my file:
[龙岩新罗35千伏大池电站10千伏大和大和#3配变新建工程汇总出库单.XLSX](https://github.com/SheetJS/js-xlsx/files/809666/35.10.3.XLSX)
i dont know what different in this file.

code:
var workBook = XLSX.readFile('龙岩新罗35千伏大池电站10千伏大和大和#3配变新建工程汇总出库单.XLSX');

**Comment by SheetJSDev** [comment] 2017-03-01 06:50
So this file is actually a tab-delimited text with a UTF16-LE encoding.  It is something a general CSV parser should handle.  Gotta love how Excel just works in this case.  We will add a CSV/TSV parser to js-xlsx at some point, hopefully soon.

**Comment by SHocker-Yu** [comment] 2017-03-01 07:49
@SheetJSDev Thank U! Yeah,it is a CSV file in fact.

**Comment by SheetJSDev** [comment] 2017-03-01 08:58
Closing as duplicate of https://github.com/SheetJS/js-xlsx/issues/489

**Closed by SheetJSDev** 2017-03-01 08:58 UTC
