### ISSUE TITLE
SCRIPT5022: DataCloneError  js-xlsx, line 131 character 3

### ISSUE THREAD

**Issue by Sankrish** [SheetJS/js-xlsx#247] opened 2015-06-09 10:04 UTC
Demo and application works fine in FF and Chrome . but when tried with IE 10 and other versions . I get the error as 

SCRIPT5022: DataCloneError 
js-xlsx, line 131 character 3

NOTE : I have added shim.js to the application am trying and it is loaded in the browser too 

Any help is appreciated!!

**Comment by ergh99** [comment] 2015-06-24 21:12
This won't be fixed...
https://connect.microsoft.com/IE/feedback/details/783468/ie10-window-pos

**Comment by 796289** [comment] 2015-07-16 16:10
Happen on IE 11 too. Is there any workaround for this?

**Comment by ergh99** [comment] 2015-07-16 16:25
My experimenting leads me to believe this happens as a result of using Web Workers.  This isn't necessary for the workbook parsing functionality however.  Can't remember how to turn them off, but the demo page has a check box to turn them off that you can inspect.

**Comment by SheetJSDev** [comment] 2015-07-16 19:30
The DataCloneError as a whole seems to be related to the use of Transferables.  In the repo demo http://oss.sheetjs.com/js-xlsx can you reproduce the error if you uncheck the "Use Transferables" checkbox but leave the Web Workers checkbox checked?

Relevant IE discussion: http://connect.microsoft.com/IE/feedback/details/783468/ie10-window-postmessage-throws-datacloneerror-for-transferrable-arraybuffers

**Comment by reviewher** [comment] 2017-03-13 02:45
Copied content to wiki page: https://github.com/SheetJS/js-xlsx/wiki/Browser-Errors

**Closed by reviewher** 2017-03-13 02:45 UTC
