### ISSUE TITLE
Number changed to date format

### ISSUE THREAD

**Issue by samighawi** [SheetJS/js-xlsx#688] opened 2017-06-13 14:09 UTC
Hello,

I am currently using xlsx-js to export an HTML table and works well with one exception; One number is changed to date format.

Please find below the code example:
https://jsfiddle.net/samighawi/L2x5zm5x/2/

At cell G1, the number 12.11% is converted to "11/12/2001 01:00:00" in Excel. Any ideas how to solve this problem? Please note that the table is dynamic and I don't know whether it is a number or date format. I'd rather turn off formatting if it causes problems and keep it as General.

Thanks

**Comment by reviewher** [comment] 2017-06-13 16:14
Duplicate of https://github.com/SheetJS/js-xlsx/issues/673.  It looks like a fix is in the works

**Closed by reviewher** 2017-06-13 16:14 UTC
