### ISSUE TITLE
insert row before header

### ISSUE THREAD

**Issue by samuelkavin** [SheetJS/js-xlsx#669] opened 2017-05-29 05:22 UTC
@SheetJSDev is it possible insert custom 3 row before header? something like this:
Example: A1, A2, A3 
<img width="1003" alt="screen shot 2017-05-24 at 6 16 18 pm" src="https://cloud.githubusercontent.com/assets/5300968/26537398/ba67f512-4471-11e7-88bd-e47f29fd7cc2.png">

**Comment by jomel** [comment] 2017-05-29 14:03
Related to #301

**Comment by reviewher** [comment] 2017-06-12 16:02
Duplicate of #301

**Closed by reviewher** 2017-06-12 16:02 UTC
