### ISSUE TITLE
sheet_to_row_object_array is not documented

### ISSUE THREAD

**Issue by dskrvk** [SheetJS/js-xlsx#424] opened 2016-06-08 16:58 UTC
Function needs proper documentation, including what options it takes and e.g. the behavior when a sheet contains multiple columns with the same name.

**Comment by gbhasha** [comment] 2016-06-26 20:49
+1.

Only below utils are mentioned in the readme file. 

sheet_to_json converts a workbook object to an array of JSON objects.
sheet_to_csv generates delimiter-separated-values output
sheet_to_formulae generates a list of the formulae (with value fallbacks)

**Comment by LeonardoPatignio** [comment] 2016-08-05 18:08
sheet_to_row_object_array is a parser function of sheet_to_json which both of them given a 'sheet' plus 'options'( optional param) and returns an 'array  of rows with w as value inside'

```
function sheet_to_row_object_array(sheet, opts) {
return sheet_to_json(sheet, opts != null ? opts : {});
}
```

**Comment by reviewher** [comment] 2017-01-03 19:02
Looking at the history, originally there were separate functions to convert worksheets to different types of functions.  As the use cases expanded, the complete function `sheet_to_json` took shape, but the original accessor was not removed.  I am sure it will be removed in the future and the README will be updated to note that it is an alias.

@sheetjsdev please add a note to README and close the issue

**Closed** 2017-03-10 23:44 UTC

**Comment by SheetJSDev** [comment] 2017-03-10 23:47
https://github.com/SheetJS/js-xlsx#json we included a section describing the sheet_to_* functions with some examples.

**Comment by dskrvk** [comment] 2017-03-10 23:51
Awesome, thanks!

**Comment by gabeno** [comment] 2017-03-16 13:32
I had to specify the sheet I am interested in thus:

```js
console.log(X.utils.sheet_to_json(_ws.Sheet.Sheet1)
```

It is not clear in the docs. So is this the intended behaviour missing in the docs or I am missing something myself?

**Comment by SheetJSDev** [comment] 2017-03-16 14:08
@gabeno there's one general line in the enclosing section:

https://github.com/SheetJS/js-xlsx#utility-functions

> The `sheet_to_*` functions accept a worksheet and an optional options object.

That line probably should be included in each of the subsections.
