### ISSUE TITLE
 Cannot find file [Content_Types].xml in zip - SAPUI5

### ISSUE THREAD

**Issue by shriyaEsha** [SheetJS/js-xlsx#744] opened 2017-07-21 17:35 UTC
I'm trying to convert an Excel sheet to JSON using XLSX.js. I've included both XLSX.js and jszip.js in my project making sure that jszip is loaded first.
I get a console error stating that ** Cannot find file [Content_Types].xml in zip**

The full error is as follows:
XLSX.js?eval:1559 Uncaught Error: Cannot find file [Content_Types].xml in zip
    at getzipfile (XLSX.js?eval:1559)
    at getzipstr (XLSX.js?eval:1570)
    at parse_zip (XLSX.js?eval:17079)
    at read_zip (XLSX.js?eval:17392)
    at Object.readSync [as read] (XLSX.js?eval:17417)
    at XMLHttpRequest.oReq.onload (AddAccessFileDetails.controller.js?eval:76)

**Comment by SheetJSDev** [comment] 2017-07-25 22:21
This is most likely a file-specific issue.  Can you share the exact file that triggered this error?  You can share ZIP files over GH.

FYI: You can elicit that error by passing a valid ZIP file that isn't XLSX or ODS. 
 For example, https://github.com/SheetJS/js-xlsx/archive/v0.10.8.zip will reproduce the error.

**Comment by reviewher** [comment] 2017-08-07 16:46
@shriyaEsha closing for now, if you can share a file please post or email and we will reopen

**Closed by reviewher** 2017-08-07 16:46 UTC

**Comment by shriyaEsha** [comment] 2017-08-08 18:05
[SUF-UET-NTR.xlsx](https://github.com/SheetJS/js-xlsx/files/1209126/SUF-UET-NTR.xlsx)

Sorry for the delay! This is the file.

**Comment by SheetJSDev** [comment] 2017-08-08 18:09
Thanks for following up! I can't open the file in Excel 2013 or in Excel 2016 -- both report that the file is corrupt and data cannot be recovered.  Does it actually work for you in Excel?  Maybe the upload was corrupted?

**Comment by shriyaEsha** [comment] 2017-08-08 18:11
I'll try a different upload now. This *is *the file. You're right. Let me
try a different file.

Cheers!
Shriya

**Comment by shriyaEsha** [comment] 2017-08-08 18:12
This is the actual file.

Cheers!
Shriya

**Comment by SheetJSDev** [comment] 2017-08-08 18:16
@shriyaEsha github doesn't automatically expose attachments when you reply to the issue emails -- can you send the file in an email to dev@sheetjs.com

**Comment by halcharger** [comment] 2017-10-18 13:08
@SheetJSDev I've got the exact same error as experience by @shriyaEsha 

My xlsx file is attached.
[Test File 1.xlsx](https://github.com/SheetJS/js-xlsx/files/1394692/Test.File.1.xlsx)

**Comment by SheetJSDev** [comment] 2017-10-18 13:14
@halcharger can't reproduce the error with http://oss.sheetjs.com/js-xlsx/ locally -- can you test if that works for you?  If it works, verify that the file is being downloaded properly (if you are using a web service and downloading the file with XMLHttpRequest)

**Comment by halcharger** [comment] 2017-10-18 13:24
@SheetJSDev my file works with oss.sheetjs.com/js-xlsx which I would expect as I mentioned i was able to get it working with a vanilla html/js web page, my problem is getting it working with SAPUI5.

**Comment by SheetJSDev** [comment] 2017-10-18 13:30
@halcharger if it's working normally but not in SAPUI5, then it's most likely a problem with SAPUI5.  In @shriyaEsha 's case it was an issue with the XMLHttpRequest and the actual data that the browser was seeing.  Check your browser to ensure that you are actually receiving a valid file.

**Comment by stefaneidelloth** [comment] 2020-11-15 09:28
I got that error message because I imported xlsx.min.js instead of xlsx.full.min.js
