### ISSUE TITLE
Correct way to save as xls file?

### ISSUE THREAD

**Issue by guojiaqi1027** [SheetJS/js-xlsx#1245] opened 2018-08-28 08:21 UTC
I'm using XLSX.writeFile to save a workbook file. As xlsx file is working fine, when I try to save the file as a xls file (by change the filename to XXX.xls), the saved file cannot be opened by both Excel and Numbers on Mac.

Is there a format issue on xls file? I attached my code below:

```
const data = [];
data.push(['label1', 'label2']);
data.push(['data1', 'data2']);
const book = XLSX.utils.book_new();
const sheet = XLSX.utils.aoa_to_sheet(data);
XLSX.utils.book_append_sheet(book, sheet, 'sheet1');
XLSX.writeFile(book, `${filename}.xls`);
```

**Comment by SheetJSDev** [comment] 2018-08-28 21:51
This is working with Excel:

```js
//const XLSX = require("xlsx"); // uncomment if using nodejs
const filename = "issue1245";
const data = [];
data.push(['label1', 'label2']);
data.push(['data1', 'data2']);
const book = XLSX.utils.book_new();
const sheet = XLSX.utils.aoa_to_sheet(data);
XLSX.utils.book_append_sheet(book, sheet, 'sheet1');
XLSX.writeFile(book, `${filename}.xls`);
```

Numbers is indeed erroring, but this is a dupe of https://github.com/SheetJS/js-xlsx/issues/1188

**Closed by SheetJSDev** 2018-08-28 21:51 UTC
