### ISSUE TITLE
anyone can help me with xlsx.full.js

### ISSUE THREAD

**Issue by zhubj** [SheetJS/js-xlsx#1633] opened 2019-09-19 16:36 UTC
I am a sfdc developer, and I found this can't work with salesforce lightning web component,
after a lot of searching work, I found that because two reason :
1,  [Uncaught TypeError: jszip is not a constructor #872](https://github.com/SheetJS/js-xlsx/issues/872)
2,need to add  window.XLSX = XLSX; in xlsx.js

because I can't find xlsx.full.js, so I can't finish step2.
please help , thanks

**Comment by SheetJSDev** [comment] 2019-09-19 16:41
Dupe of https://github.com/SheetJS/js-xlsx/issues/1445

**Closed by SheetJSDev** 2019-09-19 16:41 UTC
